usuarios/urls.py
from django.conf.urls import url
from . import views

app_name = "usuarios"


urlpatterns = [
    url(r'logout/$', views.logout_user, name="logout" ),
    url(r'login/$', views.login_user, name="login"),
    url(r'crear_usuario/$', views.guardar_usuario, name="crear_usuario"),
    url(r'fondear_cuenta/$', views.fondear_cuenta_perfil, name="fondear_cuenta")
]

venta/urls.py
from django.conf.urls import url
from . import views

app_name = "venta"


urlpatterns = [
    url(r'^$', views.index_dashboard, name="dashboard" )
]

wee_burgers/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from basicos import views
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name="index"),
    url(r'^usuarios/', include('usuarios.urls')),
    url(r'^ventas/',  include('venta.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basicos/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

usuarios/models/perfil.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Perfil(models.Model):
    """Model definition for Perfil."""

    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    direccion = models.CharField(max_length=350)
    telefono = models.CharField(max_length=14)

    class Meta:
        """Meta definition for Perfil."""

        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfiles'

    def __unicode__(self):
        """Unicode representation of Perfil."""
        return self.usuario.first_name

venta/models/categoria.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Categoria(models.Model):
    """Model definition for Categoria."""

    nombre = models.CharField(max_length=50)

    class Meta:
        """Meta definition for Categoria."""

        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __unicode__(self):
        """Unicode representation of Categoria."""
        return self.nombre

venta/models/pedido.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Pedido(models.Model):
    """Model definition for Pedido."""

    ESTATUS = (
        ('cl', 'Colocado'),
        ('p', 'En Proceso'),
        ('t', 'Terminado'),
        ('e', 'Entregado'),
        ('c', 'Cancelado')
    )

    cliente = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now=True)
    total_pagar = models.DecimalField(max_digits=11, decimal_places=2)
    estatus = models.CharField(max_length=10, choices=ESTATUS, default="colocado")

    

    class Meta:
        """Meta definition for Pedido."""

        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

    def __unicode__(self):
        """Unicode representation of Pedido."""
        return "Cliente: {} Fecha {}".format(self.cliente, self.fecha)

venta/models/producto.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from categoria import Categoria

class Producto(models.Model):
    """Model definition for Producto."""

    
    nombre = models.CharField(max_length=50)
    precio = models.DecimalField(max_digits=7, decimal_places=2)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    foto_producto = models.ImageField(upload_to='imagen_producto/', blank=True, null=True)

    class Meta:
        """Meta definition for Producto."""

        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

    def __unicode__(self):
        """Unicode representation of Producto."""
        return self.nombre

venta/models/productos_pedido.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from producto import Producto
from pedido import Pedido

class ProductosPedido(models.Model):
    """Model definition for ProductosPedido."""
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    precio = models.DecimalField(max_digits=10 , decimal_places=2)
    cantidad = models.IntegerField()
    

    class Meta:
        """Meta definition for ProductosPedido."""

        verbose_name = 'ProductosPedido'
        verbose_name_plural = 'ProductosPedidos'

    def __unicode__(self):
        """Unicode representation of ProductosPedido."""
        return "Pedido: {}  Producto: {}".format(self.pedido, self.producto)

usuarios/forms.py
from django import forms
from django.contrib.auth.models import  User

from .models import Perfil

class LoginForm(forms.Form):
    username = forms.CharField(label='Username',max_length=60)
    password = forms.CharField(widget=forms.PasswordInput)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email', 'password',)

class UsuarioForm(forms.ModelForm):
    
    class Meta:
        model = Perfil
        fields = ('direccion', 'telefono')

basicos/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

def index(request):
    return render(request, 'basicos/index.html')

usuarios/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from .forms import LoginForm, Perfil, UserForm, UsuarioForm
from .models import Perfil
from django.contrib.auth.models import User
from .usaurio import fondear_cuenta
from decimal import Decimal

def login_user(request):
    if request.user.is_authenticated():
        return redirect("venta:dashboard")
    else:
        if request.method == "POST":
            login_form = LoginForm(request.POST)
            if login_form.is_valid():
                username = login_form.cleaned_data['username']
                password = login_form.cleaned_data['password']

                user = authenticate(username=username, password=password)

                if user is not None:
                    login(request, user)
                    print "si se logeo"
                    return redirect("venta:dashboard")
                else:
                    form = LoginForm()
                    return render(request, 'usuarios/login.html', {'form': form})
        else:
            form = LoginForm()
        
            return render(request, 'usuarios/login.html', {'form': form})
            
def logout_user(request):
    logout(request)
    return redirect('/')

def guardar_usuario(request):
    if request.method == "POST":
        user_form = UserForm(request.POST)
        usuario_form = UsuarioForm(request.POST)
        if user_form.is_valid() and usuario_form.is_valid():
            username = user_form.cleaned_data['username']
            email = user_form.cleaned_data['email']
            password = user_form.cleaned_data['password']
            user = User.objects.create_user(username,email,password)
            user.first_name =  user_form.cleaned_data['first_name']

            usuario = usuario_form.save(commit=False)
            user.save()                        
            usuario.usuario = user
            usuario.save()
            user = authenticate(username=username, password=password)
            login(request, user)
        return redirect("venta:dashboard")

    
    elif request.method == "GET":
        user_form = UserForm()
        form_usuario = UsuarioForm()
        return render(request, "usuarios/crear_usuario.html", {'user_form': user_form, 'usuario_form': form_usuario})

def fondear_cuenta_perfil(request):
    if request.method == "POST":
        monto = Decimal(request.POST.get('monto', 0))
        fondear_cuenta(request,monto)
        messages.success(request, 'Se fondeo correctamente la cuenta')
        return redirect("venta:dashboard")
    if request.method ==  "GET":
        return render(request, 'usuarios/fondear_cuenta.html')

venta/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def index_dashboard(request):
    return render(request, 'venta/index.html')

basicos/templates/basicos/index.html
{% extends 'base/main.html' %}


{% block container %}
    <div class="row">
        <div class="col col-sm-12 col-md-12 col-lg-12">
            <h4>Bienvenido a Wee Burgers</h4>

            <a href="{% url 'venta:dashboard' %}" class="btn btn-primary">Ingresar</a>
        </div>
    </div>
{% endblock container %}
    

templates/base/main.html
{% load static %}
<!DOCTYPE html>
<!-- saved from url=(0059)http://getbootstrap.com/docs/4.0/examples/starter-template/ -->
<html lang="en">
  <head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Wee Burgers</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'base/css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'base/css/starter-template.css'%}" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        {% include "base/nav/_nav.html" %}
    </nav>

    <main role="main" class="container">

      <div class="starter-template">
        {% if messages %}
          {% for message in messages %}
              <div {% if message.tags == 'success' %} 
                class="alert alert-success"
              {% elif message.tags == "error" %}
                class="alert alert-danger"
              {% endif %}
              role="alert">{{ message }}</div>
          {% endfor %}
        {% endif %}
      
        {% block container %}
            
        {% endblock container %}
          
      </div>

    </main><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'base/js/jquery.min.js' %}"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src=" {% static 'base/js/popper.min.js' %}"></script>
    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
  

</body>
</html>

templates/base/nav/_nav.html
<a class="navbar-brand" href="{% url 'index' %}">Wee Burgers</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarsExampleDefault">
  <ul class="navbar-nav mr-auto">
    {% if request.user.is_authenticated == False %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'usuarios:login' %}">Ingresar</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'usuarios:crear_usuario' %}">Crear usuario</a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'usuarios:logout' %}">Cerrar sesión</a>
        </li>
    {% endif %}
    
  </ul>
</div>

usuarios/templates/usuarios/crear_usuario.html
{% extends 'base/main.html' %}


{% block container %}
    <h4>Registra un usuario</h4>
    <div class="row">
        <div class="col s12 m6 l6">
            <form action="{% url 'usuarios:crear_usuario' %}" method="POST">
                {% csrf_token %}
                {{user_form.as_p}}
                {{usuario_form.as_p}}
                <input class="btn btn-primary" type="submit" value="Guardar">
            </form>
        </div>
    </div>
    
{% endblock container %}
    
    

usuarios/templates/usuarios/fondear_cuenta.html
{% extends "base/main.html" %}


{% block container %}
    <div class="row">
        <div class="col col-sm-12 col-md-6 col-lg-6">
            <h5>Fondear Cuenta personal con tarjeta de credito/debito</h5>
            <form action="{% url 'usuarios:fondear_cuenta' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" name="nombre_propietario" id="nombre" placeholder="Nombre que aparece en la tarjeta" class="form-control">
                </div>
                <div class="form-group">
                    <input type="text" name="numero_tarjeta" id="numero_tarjeta" max="16" placeholder="Numero de tarjeta" class="form-control">
                </div>
                <div class="form-group">
                    <input type="number" name="monto" id="monto" placeholder="Monto a depositar" class="form-control">
                </div>
                <div class="form-group">
                    <input type="submit" value="Fondear" class="btn btn-primary  teal accent-2" class="form-control">            
                </div>
            </form>
        </div>
    </div>
{% endblock container %}
    

usuarios/templates/usuarios/login.html
{% extends 'base/main.html' %}


{% block container %}
    <div class="row">
        <div class="col s12 m4 l4">
            <form action="{% url 'usuarios:login' %}" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn-primary" type="submit" value="Entrar">
            </form>
        </div>
    </div>
    
    
{% endblock container %}
    
    

venta/templates/venta/index.html
{% extends 'base/main.html' %}


{% block container %}
    <div class="row">
        <div class="col col-sm-12 col-md-12 col-lg-12">
            <h4>Soy el index dashboard</h4>
        </div>
    </div>
{% endblock container %}
    